test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
digitalocean:
  service: S3
  endpoint: https://bc-resume.nyc3.digitaloceanspaces.com/
  access_key_id: <%= Rails.application.credentials.digitalocean[:production][:aws_access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.digitalocean[:production][:aws_secret_access_key] %>
  region: us-east-1
  bucket: bc_resume